---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-project
spec:
  selector:
    matchLabels:
      app: mvn-project
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: mvn-project
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: master
        image: testdomainname.info:5050/wocheon/mvn_project
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: mvn-project-ndp
  labels:
    app: mvn-project
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    app: mvn-project